In [1]:
import cv2
import tensorflow as tf

In [2]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('mlopstask1_vgg2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('D://mlopsproject//haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
        name="None matching"
        
        if(pred[0][0]):
            name='Deepak'
        
            
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1)==13:
        video_capture.release()
        cv2.destroyAllWindows()


Using TensorFlow backend.


[[2.910394e-12 0.000000e+00 1.000000e+00]]
[[9.9998331e-01 0.0000000e+00 1.6638085e-05]]
[[2.107957e-09 0.000000e+00 1.000000e+00]]
[[1.0000000e+00 0.0000000e+00 3.1974236e-16]]
[[9.992562e-01 0.000000e+00 7.438191e-04]]
[[0.97952646 0.         0.02047355]]
[[6.725619e-26 0.000000e+00 1.000000e+00]]
[[2.5476783e-19 0.0000000e+00 1.0000000e+00]]
[[2.9341864e-32 0.0000000e+00 1.0000000e+00]]
[[3.4364154e-14 0.0000000e+00 1.0000000e+00]]
[[1.0000000e+00 0.0000000e+00 3.4017567e-09]]
[[1.0000000e+00 0.0000000e+00 4.8843063e-26]]
[[6.6238776e-10 0.0000000e+00 1.0000000e+00]]
[[2.4790654e-17 0.0000000e+00 1.0000000e+00]]
[[1.0000000e+00 0.0000000e+00 1.3782562e-09]]
[[3.127813e-32 0.000000e+00 1.000000e+00]]
[[2.2724531e-07 1.4392726e-18 9.9999976e-01]]
[[1.000000e+00 0.000000e+00 4.523778e-12]]
[[1.0000000e+00 0.0000000e+00 1.8681386e-23]]
[[1.0000000e+00 0.0000000e+00 1.0884432e-28]]
[[1.00000e+00 0.00000e+00 7.17092e-33]]
[[1.000000e+00 0.000000e+00 4.494406e-09]]
[[3.321725e-17 0.000000e

KeyboardInterrupt: 